---
title: "Exploring Data in R"
author: "Linda Angulo Lopez"
date: "04/09/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Upload & get a summary


```{r}
pollution <- read.csv("https://raw.githubusercontent.com/lindangulopez/Exploratory-Data-Analysis-by-Johns-Hopkins-University-on-COURSERA/c132b214bd7657010857bf19bb90365bc1eed249/datasets/231/data/avgpm25.csv", colClasses = c("numeric", "character",
 "factor", "numeric", "numeric"))
head(pollution)

head(pollution)
summary(pollution)

```

## Include Plots


```{r}
boxplot(pollution$pm25, col = "blue")

```


```{r}

hist(pollution$pm25, col = "green")
rug(pollution$pm25)

```


```{r}

hist(pollution$pm25, col = "green", breaks = 100)
rug(pollution$pm25)

```

```{r}

boxplot(pollution$pm25, col = "blue")
abline(h = 12)

```
## Overlay Features 
```{r}

hist(pollution$pm25, col = "green")
abline(v = 12, lwd = 2)
abline(v = median(pollution$pm25), col = "magenta", lwd = 4)

```
## Bar Graph, for a presentation
```{r}
barplot(table(pollution$region), col = "wheat", main = "Number of Counties in Each Region")


```

## Summaries of Data:
- Multiple Boxplots Multiple Boxplots
```{r}
boxplot(pm25 ~ region, data = pollution, col = "red")

```

- Histograms Multiple Histograms

```{r}

par(mfrow = c(2, 1), mar = c(4, 4, 2, 1))
hist(subset(pollution, region == "east")$pm25, col = "green")
hist(subset(pollution, region == "west")$pm25, col = "green")

```

- Scatterplot Scatterplot
```{r}
with(pollution, plot(latitude, pm25))
abline(h = 12, lwd = 2, lty = 2)
```

- Scatterplot - Using Color
```{r}
with(pollution, plot(latitude, pm25, col = region))
abline(h = 12, lwd = 2, lty = 2)
```

- Multiple Scatterplots Multiple Scatterplots
```{r}
par(mfrow = c(1, 2), mar = c(5, 4, 2, 1))
with(subset(pollution, region == "west"), plot(latitude, pm25, main = "West"))
with(subset(pollution, region == "east"), plot(latitude, pm25, main = "East"))
```

#### [by Linda, September 2020 ](https://www.linkedin.com/in/lindangulopez/)